spring:
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.31.125:3306/debug?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
        slave: #核桃数据库
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.31.125:3306/debug?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
      primary: master
  redis:
    host: 192.168.31.125 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com:
      example: debug
