package com.example.modules.wnhis.pojo;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.io.Serializable;

/**
 * @TableName his_extractionlog
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("his_extractionlog")
@ApiModel(value="接口调用日志", description="日志表")
public class HisExtractionlog implements Serializable {

    @TableId(value = "uuid", type = IdType.AUTO)
    private String uuid;

    /**
     * 业务编号 一次请求一个编号
     *
     * @mbg.generated Tue Mar 16 13:42:56 CST 2021
     */
    private String no;

    /**
     * 医院编号
     *
     * @mbg.generated Tue Mar 16 13:42:56 CST 2021
     */
    private String hospitalno;

    /**
     * hisId
     *
     * @mbg.generated Tue Mar 16 13:42:56 CST 2021
     */
    private String hisid;

    /**
     * 病人类别
     *
     * @mbg.generated Tue Mar 16 13:42:56 CST 2021
     */
    private String brlb;

    /**
     * 接口信息
     *
     * @mbg.generated Tue Mar 16 13:42:56 CST 2021
     */
    private String method;

    /**
     * 请求参数
     *
     * @mbg.generated Tue Mar 16 13:42:56 CST 2021
     */
    private String param;

    /**
     * his返回参数
     *
     * @mbg.generated Tue Mar 16 13:42:56 CST 2021
     */
    private String response;

    /**
     * 调用接口返回参数
     *
     * @mbg.generated Tue Mar 16 13:42:56 CST 2021
     */
    private String methodresponse;

    /**
     * 创建时间
     *
     * @mbg.generated Tue Mar 16 13:42:56 CST 2021
     */
    private Long createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table his_extractionlog
     *
     * @mbg.generated Tue Mar 16 13:42:56 CST 2021
     */
    private static final long serialVersionUID = 1L;
}
